# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerCustomer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registercustomer',
            old_name='isActive',
            new_name='F_Name',
        ),
        migrations.RemoveField(
            model_name='registercustomer',
            name='regDate',
        ),
    ]
