# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registerAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_Name', models.CharField(max_length=250)),
                ('L_Name', models.CharField(max_length=250)),
                ('Phonenumber', models.CharField(max_length=250)),
                ('Email', models.CharField(max_length=250)),
                ('County', models.CharField(max_length=250)),
                ('Constituency', models.CharField(max_length=250)),
                ('Locality', models.CharField(max_length=250)),
                ('isActive', models.CharField(max_length=250)),
                ('regDate', models.CharField(max_length=250)),
            ],
        ),
    ]
